//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the armcontrol_demo_pkg package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __armcontrol_demo_pkg__DYNAMICPARAMCONFIG_H__
#define __armcontrol_demo_pkg__DYNAMICPARAMCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace armcontrol_demo_pkg
{
  class DynamicParamConfigStatics;

  class DynamicParamConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(DynamicParamConfig &config, const DynamicParamConfig &max, const DynamicParamConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const DynamicParamConfig &config1, const DynamicParamConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, DynamicParamConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const DynamicParamConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, DynamicParamConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const DynamicParamConfig &config) const = 0;
      virtual void getValue(const DynamicParamConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T DynamicParamConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T DynamicParamConfig::* field;

      virtual void clamp(DynamicParamConfig &config, const DynamicParamConfig &max, const DynamicParamConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const DynamicParamConfig &config1, const DynamicParamConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, DynamicParamConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const DynamicParamConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, DynamicParamConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const DynamicParamConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const DynamicParamConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, DynamicParamConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, DynamicParamConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<DynamicParamConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(DynamicParamConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("motor_state"==(*_i)->name){motor_state = boost::any_cast<std::string>(val);}
        if("arm_mode"==(*_i)->name){arm_mode = boost::any_cast<std::string>(val);}
        if("Emergency_Stop"==(*_i)->name){Emergency_Stop = boost::any_cast<bool>(val);}
        if("drag_teachin"==(*_i)->name){drag_teachin = boost::any_cast<std::string>(val);}
        if("drag_teachin_name"==(*_i)->name){drag_teachin_name = boost::any_cast<std::string>(val);}
        if("joint1_angle"==(*_i)->name){joint1_angle = boost::any_cast<double>(val);}
        if("joint2_angle"==(*_i)->name){joint2_angle = boost::any_cast<double>(val);}
        if("joint3_angle"==(*_i)->name){joint3_angle = boost::any_cast<double>(val);}
        if("joint4_angle"==(*_i)->name){joint4_angle = boost::any_cast<double>(val);}
        if("joint5_angle"==(*_i)->name){joint5_angle = boost::any_cast<double>(val);}
        if("joint6_angle"==(*_i)->name){joint6_angle = boost::any_cast<double>(val);}
        if("arm_position_x"==(*_i)->name){arm_position_x = boost::any_cast<double>(val);}
        if("arm_position_y"==(*_i)->name){arm_position_y = boost::any_cast<double>(val);}
        if("arm_position_z"==(*_i)->name){arm_position_z = boost::any_cast<double>(val);}
        if("arm_orientation_roll"==(*_i)->name){arm_orientation_roll = boost::any_cast<double>(val);}
        if("arm_orientation_pitch"==(*_i)->name){arm_orientation_pitch = boost::any_cast<double>(val);}
        if("arm_orientation_yaw"==(*_i)->name){arm_orientation_yaw = boost::any_cast<double>(val);}
      }
    }

    std::string motor_state;
std::string arm_mode;
bool Emergency_Stop;
std::string drag_teachin;
std::string drag_teachin_name;
double joint1_angle;
double joint2_angle;
double joint3_angle;
double joint4_angle;
double joint5_angle;
double joint6_angle;
double arm_position_x;
double arm_position_y;
double arm_position_z;
double arm_orientation_roll;
double arm_orientation_pitch;
double arm_orientation_yaw;

    bool state;
    std::string name;

    
}groups;



//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string motor_state;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string arm_mode;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool Emergency_Stop;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string drag_teachin;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string drag_teachin_name;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double joint1_angle;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double joint2_angle;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double joint3_angle;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double joint4_angle;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double joint5_angle;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double joint6_angle;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double arm_position_x;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double arm_position_y;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double arm_position_z;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double arm_orientation_roll;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double arm_orientation_pitch;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double arm_orientation_yaw;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("DynamicParamConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (size_t i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (size_t i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (size_t i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (size_t i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const DynamicParamConfig &__max__ = __getMax__();
      const DynamicParamConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const DynamicParamConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const DynamicParamConfig &__getDefault__();
    static const DynamicParamConfig &__getMax__();
    static const DynamicParamConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const DynamicParamConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void DynamicParamConfig::ParamDescription<std::string>::clamp(DynamicParamConfig &config, const DynamicParamConfig &max, const DynamicParamConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class DynamicParamConfigStatics
  {
    friend class DynamicParamConfig;

    DynamicParamConfigStatics()
    {
DynamicParamConfig::GroupDescription<DynamicParamConfig::DEFAULT, DynamicParamConfig> Default("Default", "", 0, 0, true, &DynamicParamConfig::groups);
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.motor_state = "";
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.motor_state = "";
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.motor_state = "disable";
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<std::string>("motor_state", "str", 0, "控制机械臂电机开启或关闭", "{'enum': [{'name': 'disable', 'type': 'str', 'value': 'disable', 'srcline': 8, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '电机失能，进入被动阻尼状态', 'ctype': 'std::string', 'cconsttype': 'const char * const'}, {'name': 'enable', 'type': 'str', 'value': 'enable', 'srcline': 9, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '电机使能，可以控制', 'ctype': 'std::string', 'cconsttype': 'const char * const'}], 'enum_description': '控制机械臂电机开启或关闭'}", &DynamicParamConfig::motor_state)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<std::string>("motor_state", "str", 0, "控制机械臂电机开启或关闭", "{'enum': [{'name': 'disable', 'type': 'str', 'value': 'disable', 'srcline': 8, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '电机失能，进入被动阻尼状态', 'ctype': 'std::string', 'cconsttype': 'const char * const'}, {'name': 'enable', 'type': 'str', 'value': 'enable', 'srcline': 9, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '电机使能，可以控制', 'ctype': 'std::string', 'cconsttype': 'const char * const'}], 'enum_description': '控制机械臂电机开启或关闭'}", &DynamicParamConfig::motor_state)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.arm_mode = "";
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.arm_mode = "";
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.arm_mode = "arm_sleep";
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<std::string>("arm_mode", "str", 0, "控制机械臂处于何种控制模式", "{'enum': [{'name': 'arm_sleep', 'type': 'str', 'value': 'arm_sleep', 'srcline': 12, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '机械臂收拢到休眠位置，解除位置控制进入阻尼模式，适合长时间保持', 'ctype': 'std::string', 'cconsttype': 'const char * const'}, {'name': 'arm_control_demo', 'type': 'str', 'value': 'arm_control_demo', 'srcline': 13, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '机械臂控制指令不经过moveit规划,实现点动和拖动示教功能', 'ctype': 'std::string', 'cconsttype': 'const char * const'}, {'name': 'arm_control_moveit_fk', 'type': 'str', 'value': 'arm_control_moveit_fk', 'srcline': 14, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '使用moveit进行正运动学规划,此时输入量为各关节角度', 'ctype': 'std::string', 'cconsttype': 'const char * const'}, {'name': 'arm_control_moveit_ik', 'type': 'str', 'value': 'arm_control_moveit_ik', 'srcline': 15, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '使用moveit进行逆运动学规划,此时输入量为末端位姿', 'ctype': 'std::string', 'cconsttype': 'const char * const'}], 'enum_description': '控制机械臂处于何种控制模式'}", &DynamicParamConfig::arm_mode)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<std::string>("arm_mode", "str", 0, "控制机械臂处于何种控制模式", "{'enum': [{'name': 'arm_sleep', 'type': 'str', 'value': 'arm_sleep', 'srcline': 12, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '机械臂收拢到休眠位置，解除位置控制进入阻尼模式，适合长时间保持', 'ctype': 'std::string', 'cconsttype': 'const char * const'}, {'name': 'arm_control_demo', 'type': 'str', 'value': 'arm_control_demo', 'srcline': 13, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '机械臂控制指令不经过moveit规划,实现点动和拖动示教功能', 'ctype': 'std::string', 'cconsttype': 'const char * const'}, {'name': 'arm_control_moveit_fk', 'type': 'str', 'value': 'arm_control_moveit_fk', 'srcline': 14, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '使用moveit进行正运动学规划,此时输入量为各关节角度', 'ctype': 'std::string', 'cconsttype': 'const char * const'}, {'name': 'arm_control_moveit_ik', 'type': 'str', 'value': 'arm_control_moveit_ik', 'srcline': 15, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '使用moveit进行逆运动学规划,此时输入量为末端位姿', 'ctype': 'std::string', 'cconsttype': 'const char * const'}], 'enum_description': '控制机械臂处于何种控制模式'}", &DynamicParamConfig::arm_mode)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.Emergency_Stop = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.Emergency_Stop = 1;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.Emergency_Stop = 0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<bool>("Emergency_Stop", "bool", 0, "急停", "", &DynamicParamConfig::Emergency_Stop)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<bool>("Emergency_Stop", "bool", 0, "急停", "", &DynamicParamConfig::Emergency_Stop)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.drag_teachin = "";
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.drag_teachin = "";
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.drag_teachin = "false";
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<std::string>("drag_teachin", "str", 0, "拖动示教", "{'enum': [{'name': 'false', 'type': 'str', 'value': 'false', 'srcline': 18, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '停止', 'ctype': 'std::string', 'cconsttype': 'const char * const'}, {'name': 'write', 'type': 'str', 'value': 'write', 'srcline': 19, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '写入', 'ctype': 'std::string', 'cconsttype': 'const char * const'}, {'name': 'read', 'type': 'str', 'value': 'read', 'srcline': 20, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '读出', 'ctype': 'std::string', 'cconsttype': 'const char * const'}], 'enum_description': '拖动示教'}", &DynamicParamConfig::drag_teachin)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<std::string>("drag_teachin", "str", 0, "拖动示教", "{'enum': [{'name': 'false', 'type': 'str', 'value': 'false', 'srcline': 18, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '停止', 'ctype': 'std::string', 'cconsttype': 'const char * const'}, {'name': 'write', 'type': 'str', 'value': 'write', 'srcline': 19, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '写入', 'ctype': 'std::string', 'cconsttype': 'const char * const'}, {'name': 'read', 'type': 'str', 'value': 'read', 'srcline': 20, 'srcfile': '/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg', 'description': '读出', 'ctype': 'std::string', 'cconsttype': 'const char * const'}], 'enum_description': '拖动示教'}", &DynamicParamConfig::drag_teachin)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.drag_teachin_name = "";
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.drag_teachin_name = "";
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.drag_teachin_name = "/home/ubuntu/ROS/roboarm3_ws/src/dm_motor/txt/drag_teachin_1.txt";
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<std::string>("drag_teachin_name", "str", 0, "拖动示教存储文件名", "", &DynamicParamConfig::drag_teachin_name)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<std::string>("drag_teachin_name", "str", 0, "拖动示教存储文件名", "", &DynamicParamConfig::drag_teachin_name)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.joint1_angle = -3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.joint1_angle = 3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.joint1_angle = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("joint1_angle", "double", 0, "关节1角度", "", &DynamicParamConfig::joint1_angle)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("joint1_angle", "double", 0, "关节1角度", "", &DynamicParamConfig::joint1_angle)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.joint2_angle = -3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.joint2_angle = 3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.joint2_angle = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("joint2_angle", "double", 0, "关节2角度", "", &DynamicParamConfig::joint2_angle)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("joint2_angle", "double", 0, "关节2角度", "", &DynamicParamConfig::joint2_angle)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.joint3_angle = -3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.joint3_angle = 3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.joint3_angle = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("joint3_angle", "double", 0, "关节3角度", "", &DynamicParamConfig::joint3_angle)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("joint3_angle", "double", 0, "关节3角度", "", &DynamicParamConfig::joint3_angle)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.joint4_angle = -3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.joint4_angle = 3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.joint4_angle = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("joint4_angle", "double", 0, "关节4角度", "", &DynamicParamConfig::joint4_angle)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("joint4_angle", "double", 0, "关节4角度", "", &DynamicParamConfig::joint4_angle)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.joint5_angle = -3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.joint5_angle = 3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.joint5_angle = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("joint5_angle", "double", 0, "关节5角度", "", &DynamicParamConfig::joint5_angle)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("joint5_angle", "double", 0, "关节5角度", "", &DynamicParamConfig::joint5_angle)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.joint6_angle = -3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.joint6_angle = 3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.joint6_angle = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("joint6_angle", "double", 0, "关节6角度", "", &DynamicParamConfig::joint6_angle)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("joint6_angle", "double", 0, "关节6角度", "", &DynamicParamConfig::joint6_angle)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.arm_position_x = -0.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.arm_position_x = 0.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.arm_position_x = 0.2;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("arm_position_x", "double", 0, "末端x坐标", "", &DynamicParamConfig::arm_position_x)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("arm_position_x", "double", 0, "末端x坐标", "", &DynamicParamConfig::arm_position_x)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.arm_position_y = -0.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.arm_position_y = 0.5;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.arm_position_y = 0.2;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("arm_position_y", "double", 0, "末端y坐标", "", &DynamicParamConfig::arm_position_y)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("arm_position_y", "double", 0, "末端y坐标", "", &DynamicParamConfig::arm_position_y)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.arm_position_z = -0.6;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.arm_position_z = 0.7;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.arm_position_z = 0.3;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("arm_position_z", "double", 0, "末端z坐标", "", &DynamicParamConfig::arm_position_z)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("arm_position_z", "double", 0, "末端z坐标", "", &DynamicParamConfig::arm_position_z)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.arm_orientation_roll = -3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.arm_orientation_roll = 3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.arm_orientation_roll = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("arm_orientation_roll", "double", 0, "末端姿态roll角", "", &DynamicParamConfig::arm_orientation_roll)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("arm_orientation_roll", "double", 0, "末端姿态roll角", "", &DynamicParamConfig::arm_orientation_roll)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.arm_orientation_pitch = -3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.arm_orientation_pitch = 3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.arm_orientation_pitch = 1.57;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("arm_orientation_pitch", "double", 0, "末端姿态pitch角", "", &DynamicParamConfig::arm_orientation_pitch)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("arm_orientation_pitch", "double", 0, "末端姿态pitch角", "", &DynamicParamConfig::arm_orientation_pitch)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.arm_orientation_yaw = -3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.arm_orientation_yaw = 3.14;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.arm_orientation_yaw = 0.0;
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("arm_orientation_yaw", "double", 0, "末端姿态yaw角度", "", &DynamicParamConfig::arm_orientation_yaw)));
//#line 292 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(DynamicParamConfig::AbstractParamDescriptionConstPtr(new DynamicParamConfig::ParamDescription<double>("arm_orientation_yaw", "double", 0, "末端姿态yaw角度", "", &DynamicParamConfig::arm_orientation_yaw)));
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(DynamicParamConfig::AbstractGroupDescriptionConstPtr(new DynamicParamConfig::GroupDescription<DynamicParamConfig::DEFAULT, DynamicParamConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<DynamicParamConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<DynamicParamConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<DynamicParamConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    DynamicParamConfig __max__;
    DynamicParamConfig __min__;
    DynamicParamConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const DynamicParamConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static DynamicParamConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &DynamicParamConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const DynamicParamConfig &DynamicParamConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const DynamicParamConfig &DynamicParamConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const DynamicParamConfig &DynamicParamConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<DynamicParamConfig::AbstractParamDescriptionConstPtr> &DynamicParamConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<DynamicParamConfig::AbstractGroupDescriptionConstPtr> &DynamicParamConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const DynamicParamConfigStatics *DynamicParamConfig::__get_statics__()
  {
    const static DynamicParamConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = DynamicParamConfigStatics::get_instance();

    return statics;
  }

//#line 8 "/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg"
      const char * const DynamicParam_disable = "disable";
//#line 9 "/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg"
      const char * const DynamicParam_enable = "enable";
//#line 12 "/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg"
      const char * const DynamicParam_arm_sleep = "arm_sleep";
//#line 13 "/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg"
      const char * const DynamicParam_arm_control_demo = "arm_control_demo";
//#line 14 "/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg"
      const char * const DynamicParam_arm_control_moveit_fk = "arm_control_moveit_fk";
//#line 15 "/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg"
      const char * const DynamicParam_arm_control_moveit_ik = "arm_control_moveit_ik";
//#line 18 "/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg"
      const char * const DynamicParam_false = "false";
//#line 19 "/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg"
      const char * const DynamicParam_write = "write";
//#line 20 "/home/ubuntu/ROS/roboarm3_ws/src/armcontrol_demo_pkg/cfg/DynamicParam.cfg"
      const char * const DynamicParam_read = "read";
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __DYNAMICPARAMRECONFIGURATOR_H__
