(cl:in-package dm_motor-msg)
(cl:export '(MOTOR_STATE-VAL
          MOTOR_STATE
          ARM_MODE-VAL
          ARM_MODE
          EMERGENCY_STOP-VAL
          EMERGENCY_STOP
          DRAG_TEACHIN-VAL
          DRAG_TEACHIN
          DRAG_TEACHIN_NAME-VAL
          DRAG_TEACHIN_NAME
          JOINT1_ANGLE-VAL
          JOINT1_ANGLE
          JOINT2_ANGLE-VAL
          JOINT2_ANGLE
          JOINT3_ANGLE-VAL
          JOINT3_ANGLE
          JOINT4_ANGLE-VAL
          JOINT4_ANGLE
          JOINT5_ANGLE-VAL
          JOINT5_ANGLE
          JOINT6_ANGLE-VAL
          JOINT6_ANGLE
          ARM_POSITION_X-VAL
          ARM_POSITION_X
          ARM_POSITION_Y-VAL
          ARM_POSITION_Y
          ARM_POSITION_Z-VAL
          ARM_POSITION_Z
          ARM_ORIENTATION_X-VAL
          ARM_ORIENTATION_X
          ARM_ORIENTATION_Y-VAL
          ARM_ORIENTATION_Y
          ARM_ORIENTATION_Z-VAL
          ARM_ORIENTATION_Z
          ARM_ORIENTATION_W-VAL
          ARM_ORIENTATION_W
))